"""Create product model

Revision ID: 4ec7c76a6552
Revises: 7eac088f79ff
Create Date: 2025-05-22 19:22:36.669497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ec7c76a6552'
down_revision = '7eac088f79ff'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Movie', 'Series', 'Anime', 'Documentary', name='type_enum'), nullable=False),
    sa.Column('director', sa.String(length=255), nullable=True),
    sa.Column('genre', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('Planned', 'Watching', 'Completed', name='status_enum'), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('poster', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media'))
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('media')
    # ### end Alembic commands ###
